name: Run Zig Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
      - stable
    paths:
      - "src/**"
      - "build.zig"
      - "build.zig.zon"

env:
  ZIG_VERSION: 0.14.0

jobs:
  test_macos:
    name: Tests on macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: ${{ env.ZIG_VERSION }}
      - uses: Hanaasagi/zig-action-cache@master
      - name: Build
        run: zig build --fetch
      - name: Run Tests
        run: zig build test
  test_windows:
    name: Tests on Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: ${{ env.ZIG_VERSION }}
      - uses: Hanaasagi/zig-action-cache@master
      - name: Build
        run: zig build --fetch
      - name: Run Tests
        run: zig build test
